param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [switch]$SyncFromGame,
    [switch]$AutoPush,
    [string]$CommitMessage = "",
    [string]$Branch = "main",
    [string]$GameTranslationRoot = "C:\Program Files (x86)\Steam\steamapps\common\Gamble With Your Friends\BepInEx\Translation\zh-TW"
)

$translationsRoot = Join-Path $RepoRoot "translations"
$repoZhTwRoot = Join-Path $translationsRoot "zh-TW"
$manifestPath = Join-Path $RepoRoot "manifest.txt"
$excludedSyncFileNames = @("_AutoGeneratedTranslations.txt")
$excludedManifestRelativePaths = @(".gitkeep")

if (-not (Test-Path $translationsRoot)) {
    New-Item -ItemType Directory -Path $translationsRoot -Force | Out-Null
}

if ($SyncFromGame -or $AutoPush) {
    if (-not (Test-Path $GameTranslationRoot)) {
        throw "Game translation folder not found: $GameTranslationRoot"
    }

    $preservedFiles = @{}
    foreach ($fileName in $excludedSyncFileNames) {
        $existingPath = Join-Path $repoZhTwRoot ("Text\" + $fileName)
        if (Test-Path $existingPath) {
            $preservedFiles[$existingPath] = Get-Content -LiteralPath $existingPath -Raw
        }
    }

    if (Test-Path $repoZhTwRoot) {
        Remove-Item -LiteralPath $repoZhTwRoot -Recurse -Force
    }

    New-Item -ItemType Directory -Path $repoZhTwRoot -Force | Out-Null
    $sourceRoot = (Resolve-Path -LiteralPath $GameTranslationRoot).Path
    if (-not $sourceRoot.EndsWith('\')) {
        $sourceRoot += '\'
    }

    Get-ChildItem -LiteralPath $GameTranslationRoot -Recurse -File |
        Where-Object {
            $excludedSyncFileNames -notcontains $_.Name -and
            $_.Extension -ne ".bak" -and
            $_.FullName -notmatch [regex]::Escape("\Text\Categorized\")
        } |
        ForEach-Object {
            $full = (Resolve-Path -LiteralPath $_.FullName).Path
            $relative = $full.Substring($sourceRoot.Length)
            $destination = Join-Path $repoZhTwRoot $relative
            $destinationDir = Split-Path -Parent $destination
            if (-not (Test-Path $destinationDir)) {
                New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
            }
            Copy-Item -LiteralPath $_.FullName -Destination $destination -Force
        }

    foreach ($entry in $preservedFiles.GetEnumerator()) {
        $preserveDir = Split-Path -Parent $entry.Key
        if (-not (Test-Path $preserveDir)) {
            New-Item -ItemType Directory -Path $preserveDir -Force | Out-Null
        }
        Set-Content -LiteralPath $entry.Key -Value $entry.Value -Encoding UTF8
    }

    Write-Host "Synced game translations to repo: $repoZhTwRoot"
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# relative/path|sha256|size")

Get-ChildItem -LiteralPath $translationsRoot -Recurse -File |
    Sort-Object FullName |
    ForEach-Object {
        $rootWithSlash = (Resolve-Path -LiteralPath $translationsRoot).Path
        if (-not $rootWithSlash.EndsWith('\')) {
            $rootWithSlash += '\'
        }
        $full = (Resolve-Path -LiteralPath $_.FullName).Path
        $relative = $full.Substring($rootWithSlash.Length).Replace('\','/')
        if (
            $excludedManifestRelativePaths -notcontains $relative -and
            $_.Extension -ne ".bak" -and
            $relative -notmatch '^zh-TW/Text/Categorized/' -and
            $relative -ne 'zh-TW/Text/_AutoGeneratedTranslations.txt'
        ) {
            $hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
            $lines.Add("$relative|$hash|$($_.Length)")
        }
    }

Set-Content -LiteralPath $manifestPath -Value $lines -Encoding UTF8
Write-Host "Updated manifest: $manifestPath"

if ($AutoPush) {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw "git was not found in PATH."
    }

    Push-Location $RepoRoot
    try {
        $trackedPaths = @("manifest.txt", "translations")

        $status = git status --short -- $trackedPaths
        if (-not $status) {
            Write-Host "No translation changes to commit."
            return
        }

        git add -- $trackedPaths

        if ([string]::IsNullOrWhiteSpace($CommitMessage)) {
            $CommitMessage = "Update translations $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        }

        git commit -m $CommitMessage
        git push origin $Branch
        Write-Host "Pushed translation update to origin/$Branch"
    }
    finally {
        Pop-Location
    }
}
